import { useEffect,useState } from 'react';
import { characterDebugEnabled,characterSettings,defaultCharacterSettings,updateCharacterSettings,type CharacterSettings } from '../game/character/characterSettings';
interface Telemetry{file:string;position:{x:number;y:number};yaw:number;targetYaw:number;motionState:string;clip:string;movement:{x:number;y:number};speed:number;deltaTime:number;availableClips:string[];rootMotionDetected:boolean}
const degrees=(value:number)=>(value*180/Math.PI).toFixed(1);
export function CharacterDebugPanel(){
 const [settings,setSettings]=useState<CharacterSettings>({...characterSettings}),[telemetry,setTelemetry]=useState<Telemetry>();
 useEffect(()=>{const frame=(event:Event)=>setTelemetry((event as CustomEvent<Telemetry>).detail),changed=()=>setSettings({...characterSettings});window.addEventListener('character-debug-frame',frame);window.addEventListener('character-settings-changed',changed);return()=>{window.removeEventListener('character-debug-frame',frame);window.removeEventListener('character-settings-changed',changed)}},[]);
 if(!characterDebugEnabled)return null;
 const set=<K extends keyof CharacterSettings>(key:K,value:CharacterSettings[K])=>updateCharacterSettings({[key]:value});
 const fields:Array<[keyof CharacterSettings,string,number,number,number]>=[['visualScale','visualScale',.4,2,.05],['visualOffsetY','visualOffsetY',-100,30,1],['rotationSpeed','rotationSpeed',1,30,.5],['walkSpeed','walkSpeed',50,600,5],['runSpeed','runSpeed',50,800,5],['walkAnimationTimeScale','walkTimeScale',.2,3,.05],['runAnimationTimeScale','runTimeScale',.2,3,.05]];
 return <aside className="character-debug-panel"><h3>Character Debug</h3><p>빨강: 캐릭터 정면 · 파랑: 이동</p><label>modelForwardOffset<select value={settings.modelForwardOffset} onChange={event=>set('modelForwardOffset',Number(event.target.value))}><option value={0}>0°</option><option value={Math.PI/2}>90°</option><option value={-Math.PI/2}>-90°</option><option value={Math.PI}>180°</option></select></label>{fields.map(([key,label,min,max,step])=><label key={key}>{label}<input type="range" min={min} max={max} step={step} value={settings[key]} onChange={event=>set(key,Number(event.target.value))}/><output>{settings[key]}</output></label>)}<dl><dt>GLB</dt><dd>{telemetry?.file??'-'}</dd><dt>position</dt><dd>{telemetry?`${telemetry.position.x.toFixed(1)}, ${telemetry.position.y.toFixed(1)}`:'-'}</dd><dt>yaw / target</dt><dd>{telemetry?`${degrees(telemetry.yaw)}° / ${degrees(telemetry.targetYaw)}°`:'-'}</dd><dt>motion / clip</dt><dd>{telemetry?`${telemetry.motionState} / ${telemetry.clip}`:'-'}</dd><dt>movement</dt><dd>{telemetry?`${telemetry.movement.x.toFixed(2)}, ${telemetry.movement.y.toFixed(2)}`:'-'}</dd><dt>speed / dt</dt><dd>{telemetry?`${telemetry.speed} / ${telemetry.deltaTime.toFixed(4)}s`:'-'}</dd><dt>clips</dt><dd>{telemetry?.availableClips.join(', ')??'-'}</dd><dt>root motion</dt><dd>{telemetry?.rootMotionDetected?'effective displacement':'position track is constant'}</dd></dl><div className="character-debug-actions"><button onClick={()=>navigator.clipboard.writeText(JSON.stringify(settings,null,2))}>설정 복사</button><button onClick={()=>updateCharacterSettings(defaultCharacterSettings)}>초기화</button></div></aside>;
}
