import {useEffect,useMemo,useState,type CSSProperties,type FormEvent} from 'react';
import {ArrowRight,Check,Crown,Heart,Image,MessageCircle,Plus,Send,Shield,Sparkles,Users,X} from 'lucide-react';
import {COMMUNITY_API_BASE_URL as API_BASE_URL} from '../config/api';
import {gameEvents} from '../game/events';
import type {UserProfile} from '../types';
import {saveClubProjectContext} from '../services/clubProjectBridge';
import {recordExperienceAction} from '../services/experienceHarness';
import './ClubStreetExperience.css';
import './ClubStreetAnchors.css';
import './ClubStreetCommunity.css';
import './ClubStreetRoofLabels.css';
import './ClubCommunityPanel.css';
import './ClubPhotoUpload.css';
import './ClubRoles.css';
import './ClubCreateForm.css';
import './ClubRoleControls.css';

type ClubMember={userId:string;name:string;role?:'chair'|'executive'|'member'};
type Club={id:string;name:string;description:string;category:string;color:string;ownerId:string;ownerName:string;members:ClubMember[];activity?:string;location?:string;schedule?:string;capacity?:number;tags?:string[];createdAt?:string};
type BoothClub=Club&{icon:string;recentActivity:string;interests:string[]};
type BoothScreenPosition={x:number;y:number;width:number;height:number;rotation:number;visible:boolean};
type FeedItem={id:string;author:string;title:string;detail:string;likes:number;comments:number;liked?:boolean;photo?:string};
type ClubTab='feed'|'album'|'info'|'members';
type LinkedProject={id:string;icon:string;name:string;status:string};

const BOOTH_COUNT=10;
const INITIAL_CLUB_COUNT=2;
const ALBUM_IMAGES=['/images/festivals/spring-flower-2026.jpg','/images/festivals/peach-2026.jpg','/images/festivals/hangeul-2026.jpg','/images/festivals/childrens-day-2026.jpg','/images/festivals/street-hangeul-2026.jpg','/images/festivals/dano-2026.jpg'];
const DEFAULT_PROJECTS:LinkedProject[]=[{id:'archive',icon:'📷',name:'세종 풍경 아카이빙',status:'활동 완료 · 후기 8개'},{id:'night',icon:'🌙',name:'정부청사 야경 기록',status:'진행 중 · 동아리원 6명 참여'}];
const iconFor=(club:Club)=>club.category.includes('사진')?'📸':club.category.includes('환경')?'🌱':club.category.includes('카페')?'☕':club.category.includes('꽃')?'🌸':'🎪';
const userIdFor=(name:string)=>`community-user-${name.trim().toLowerCase().replace(/\s+/g,'-')||'anonymous'}`;
const normalizeClub=(value:Partial<Club>):Club=>({...value,members:Array.isArray(value.members)?value.members:[],tags:Array.isArray(value.tags)?value.tags:[]} as Club);
const readError=async(response:Response)=>{try{return (await response.json() as {message?:string}).message||'요청을 처리하지 못했어요.'}catch{return '요청을 처리하지 못했어요.'}};
const seedFeed=(club:BoothClub):FeedItem[]=>club.category.includes('사진')?[
 {id:'photo-1',author:'민주',title:'수목원 사진을 업로드했어요',detail:'비 온 뒤 더 선명해진 여름 정원을 기록했습니다. · 사진 12장',likes:12,comments:3},
 {id:'photo-2',author:'하늘',title:'정부청사 야경 기록',detail:'새로운 야경 촬영 지점을 공유해요. · 사진 8장',likes:9,comments:2},
 {id:'photo-3',author:'운영팀',title:'여고 프로젝트 활동 후기',detail:'골목 풍경 아카이빙 활동 기록이 등록됐어요.',likes:17,comments:5},
]:[
 {id:'green-1',author:'초롱',title:'새로운 꽃을 발견했어요',detail:'AI 식물도감에 구절초 관찰 기록을 등록했습니다.',likes:8,comments:2},
 {id:'green-2',author:'나무',title:'공동캠퍼스 플로깅 기록',detail:'오늘 12명이 함께 캠퍼스 산책로를 정리했어요.',likes:15,comments:4},
 {id:'green-3',author:'운영팀',title:'이번 달 친환경 정보',detail:'다회용기 사용처 5곳을 새로 공유합니다.',likes:11,comments:1},
];

export function ClubStreetExperience({active,profile,onNotice}:{active:boolean;profile:UserProfile;onNotice:(message:string)=>void}){
 const [positions,setPositions]=useState<BoothScreenPosition[]>([]),[clubs,setClubs]=useState<Club[]>([]),[selected,setSelected]=useState<BoothClub|null>(null),[creatorOpen,setCreatorOpen]=useState(false),[clubName,setClubName]=useState(''),[interest,setInterest]=useState('사진'),[description,setDescription]=useState(''),[recordType,setRecordType]=useState('출사'),[saving,setSaving]=useState(false),[createError,setCreateError]=useState(''),[tab,setTab]=useState<ClubTab>('feed'),[feed,setFeed]=useState<FeedItem[]>([]),[postText,setPostText]=useState(''),[postPhoto,setPostPhoto]=useState<string|null>(null),[projects,setProjects]=useState<LinkedProject[]>(DEFAULT_PROJECTS),[projectName,setProjectName]=useState(''),[projectFormOpen,setProjectFormOpen]=useState(false);
 const userId=useMemo(()=>userIdFor(profile.nickname),[profile.nickname]);
 const [boothPickerTarget,setBoothPickerTarget]=useState<number|null>(null),[addedBooths,setAddedBooths]=useState<Record<number,BoothClub>>({});
 const openCreator=()=>{setCreateError('');setCreatorOpen(true)};
 useEffect(()=>{const changed=(value:BoothScreenPosition[])=>setPositions(value);gameEvents.on('club-booth-card-screen-positions',changed);return()=>{gameEvents.off('club-booth-card-screen-positions',changed)}},[]);
 useEffect(()=>{if(!active){setSelected(null);setCreatorOpen(false);return}const controller=new AbortController();fetch(`${API_BASE_URL}/clubs`,{signal:controller.signal}).then(response=>response.ok?response.json():[]).then(value=>setClubs((Array.isArray(value)?value:(value?.data?.items??[])).map(normalizeClub))).catch(()=>undefined);return()=>controller.abort()},[active]);
 const boothClubs=useMemo(()=>clubs.slice(0,INITIAL_CLUB_COUNT).map(club=>({...club,icon:iconFor(club),recentActivity:club.activity||club.location||'첫 활동 준비 중',interests:(club.tags?.length?club.tags:[club.category]).slice(0,2)})),[clubs]);
 const myBoothClubs=useMemo(()=>clubs.filter(club=>club.ownerId===userId).map(club=>({...club,icon:iconFor(club),recentActivity:club.activity||club.location||'첫 활동 준비 중',interests:(club.tags?.length?club.tags:[club.category]).slice(0,2)})).filter(club=>!Object.values(addedBooths).some(added=>added.id===club.id)),[clubs,userId,addedBooths]);
 const placeMyClub=(club:BoothClub)=>{if(boothPickerTarget===null)return;setAddedBooths(current=>({...current,[boothPickerTarget]:club}));setBoothPickerTarget(null);onNotice(`${club.name}을 선택한 부스에 올렸어요.`)};
 const openClub=(club:BoothClub)=>{recordExperienceAction({type:'club-open',clubName:club.name,category:club.category,tags:club.interests,activityName:club.recentActivity});setSelected(club);setTab('feed');setProjectFormOpen(false);try{const stored=JSON.parse(localStorage.getItem(`club-feed-${club.id}`)??'null') as FeedItem[]|null;setFeed(Array.isArray(stored)?stored:seedFeed(club));const savedProjects=JSON.parse(localStorage.getItem(`club-projects-${club.id}`)??'null') as LinkedProject[]|null;setProjects(Array.isArray(savedProjects)?savedProjects:DEFAULT_PROJECTS)}catch{setFeed(seedFeed(club));setProjects(DEFAULT_PROJECTS)}};
 const saveFeed=(items:FeedItem[])=>{if(!selected)return;setFeed(items);localStorage.setItem(`club-feed-${selected.id}`,JSON.stringify(items))};
 const createClub=async(event:FormEvent)=>{event.preventDefault();if(!clubName.trim()||!description.trim()||saving)return;setSaving(true);setCreateError('');try{const payload={id:`club-${userId}-${Date.now()}`,name:clubName.trim(),category:interest,description:description.trim(),activity:recordType.trim(),capacity:30,ownerId:userId,ownerName:profile.nickname,color:'#d8952f',location:'공동캠퍼스',schedule:'자율 활동',tags:[interest,recordType]},response=await fetch(`${API_BASE_URL}/clubs?action=create&payload=${encodeURIComponent(JSON.stringify(payload))}`);if(!response.ok)throw new Error(await readError(response));const body=await response.json() as {data?:{items?:Club[]},items?:Club[]},created=body.data?.items?.[0]??body.items?.[0];if(!created)throw new Error('동아리 저장 응답이 올바르지 않아요.');setClubs(current=>[...current,created]);setCreatorOpen(false);setClubName('');setDescription('');onNotice(`${created.name} 커뮤니티가 만들어졌어요. 빈 부스의 + 버튼에서 올릴 수 있어요.`)}catch(error){setCreateError(error instanceof Error?error.message:'동아리를 생성하지 못했어요.')}finally{setSaving(false)}};
 const joinClub=async(club:BoothClub)=>{try{const response=await fetch(`${API_BASE_URL}/clubs/${encodeURIComponent(club.id)}/join`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId,userName:profile.nickname})});if(!response.ok)throw new Error(await readError(response));const updated=await response.json() as Club;setClubs(current=>current.map(item=>item.id===updated.id?updated:item));setSelected(current=>current?.id===updated.id?{...current,...updated}:current);onNotice(`${club.name}에 가입했어요.`)}catch(error){onNotice(error instanceof Error?error.message:'가입하지 못했어요.')}};
 const attachPhoto=(file?:File)=>{if(!file)return;if(!file.type.startsWith('image/')){onNotice('이미지 파일만 첨부할 수 있어요.');return}if(file.size>10*1024*1024){onNotice('사진은 10MB 이하로 첨부해 주세요.');return}const reader=new FileReader();reader.onload=()=>{const source=String(reader.result),image=new window.Image();image.onload=()=>{const scale=Math.min(1,1200/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d')?.drawImage(image,0,0,canvas.width,canvas.height);setPostPhoto(canvas.toDataURL('image/jpeg',.82))};image.src=source};reader.readAsDataURL(file)};
 const addPost=(event:FormEvent)=>{event.preventDefault();if((!postText.trim()&&!postPhoto)||!selected)return;recordExperienceAction({type:'club-activity',clubName:selected.name,activityName:postText.trim()||'활동 사진 공유',category:selected.category,tags:selected.interests,note:postPhoto?'활동 사진과 후기를 피드에 공유했어요.':'활동 후기를 피드에 공유했어요.'});saveFeed([{id:`post-${Date.now()}`,author:profile.nickname,title:postText.trim()||'새 활동 사진을 공유했어요',detail:`${selected.interests[0]} 활동 기록을 공유했습니다.`,likes:0,comments:0,photo:postPhoto??undefined},...feed]);setPostText('');setPostPhoto(null);onNotice(postPhoto?'사진이 피드와 활동 앨범에 등록됐어요.':'활동 피드에 기록을 공유했어요.')};
 const toggleLike=(id:string)=>saveFeed(feed.map(item=>item.id===id?{...item,liked:!item.liked,likes:item.likes+(item.liked?-1:1)}:item));
 const uploadedPhotos=feed.filter(item=>item.photo).map(item=>({src:item.photo!,caption:item.title}));
 const albumImages=[...uploadedPhotos,...ALBUM_IMAGES.map((src,index)=>({src,caption:index<3?'수목원 출사':'커뮤니티 활동'}))];
 const isChair=selected?.ownerId===userId;
 const memberRole=(member:ClubMember)=>member.userId===selected?.ownerId?'회장':member.role==='executive'?'임원':'부원';
 const changeMemberRole=async(member:ClubMember,role:'executive'|'member')=>{if(!selected||!isChair||member.userId===selected.ownerId)return;try{const response=await fetch(`${API_BASE_URL}/clubs/${encodeURIComponent(selected.id)}/members/${encodeURIComponent(member.userId)}/role`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({actorId:userId,role})});if(!response.ok)throw new Error(await readError(response));const updated=await response.json() as Club;setClubs(current=>current.map(item=>item.id===updated.id?updated:item));setSelected(current=>current?.id===updated.id?{...current,...updated}:current);onNotice(`${member.name}님의 역할을 ${role==='executive'?'임원':'부원'}으로 변경했어요.`)}catch(error){onNotice(error instanceof Error?error.message:'역할을 변경하지 못했어요.')}};
 const addLinkedProject=(event:FormEvent)=>{event.preventDefault();if(!selected||!isChair||!projectName.trim())return;const next=[{id:`linked-${Date.now()}`,icon:'🚀',name:projectName.trim(),status:'새 프로젝트 · 준비 중'},...projects];setProjects(next);localStorage.setItem(`club-projects-${selected.id}`,JSON.stringify(next));setProjectName('');setProjectFormOpen(false);onNotice('동아리의 최근 연결 프로젝트에 추가했어요.')};
 const goToProject=()=>{if(!selected)return;saveClubProjectContext({clubId:selected.id,clubName:selected.name,icon:selected.icon,interests:selected.interests,memberNames:selected.members.map(member=>member.name),recentActivity:selected.recentActivity});gameEvents.emit('travel-to-map','project-room')};
 if(!active)return null;
 return <div className="club-street-ui club-community-ui"><section className="club-street-banner"><Sparkles size={17}/><div><b>동아리 거리제 · 커뮤니티</b><span>같은 관심사를 가진 사람들과 기록과 정보를 나눠보세요.</span></div></section><div className="club-recommendations">{positions.slice(0,BOOTH_COUNT).map((anchor,index)=>{const club=index===0?undefined:index<=INITIAL_CLUB_COUNT?boothClubs[index-1]:addedBooths[index],color=club?.color||'#d8952f',titleStyle={'--club-color':color,'--roof-height':`${anchor.height}px`,left:anchor.x,top:anchor.y} as CSSProperties;if(index===0)return <button key="creator-booth" className={`club-booth-title club-creator-booth-title ${!anchor.visible?'is-offscreen':''}`} style={titleStyle} onClick={openCreator}><Plus/><b>동아리 창설 부스</b></button>;if(club)return <button key={club.id} className={`club-booth-title ${!anchor.visible?'is-offscreen':''}`} style={titleStyle} onClick={()=>openClub(club)}><span>{club.icon}</span><b>{club.name}</b></button>;return <button key={`empty-booth-${index}`} className={`club-empty-booth-add ${!anchor.visible?'is-offscreen':''}`} style={titleStyle} onClick={()=>setBoothPickerTarget(index)} aria-label={`${index+1}번 빈 부스에 내 동아리 올리기`}><Plus/></button>})}</div>
 {selected&&<aside className="club-community-panel" style={{'--club-color':selected.color} as CSSProperties}><button className="club-panel-close" onClick={()=>setSelected(null)} aria-label="동아리 닫기"><X/></button><header className="club-panel-hero"><span>{selected.icon}</span><div><small>{selected.category} 커뮤니티</small><h2>{selected.name}</h2><p>{selected.description}</p></div></header><div className="club-panel-stats"><button className={tab==='members'?'active':''} onClick={()=>setTab('members')}><b>{selected.members.length}</b> 가입 인원</button><button className={tab==='feed'?'active':''} onClick={()=>setTab('feed')}><b>{feed.length}</b> 이번 달 활동</button><button className={tab==='album'?'active':''} onClick={()=>setTab('album')}><b>{38+uploadedPhotos.length}</b> 공유 사진</button></div><nav>{([['feed','활동 피드'],['album','활동 앨범'],['info','동아리 정보']] as [ClubTab,string][]).map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav>
  {tab==='feed'&&<section className="club-feed"><form onSubmit={addPost}><span>{profile.nickname.slice(0,1)}</span><input value={postText} onChange={event=>setPostText(event.target.value)} placeholder="사진, 후기, 새로운 정보를 공유해 보세요"/><label className="club-photo-attach" title="사진 첨부"><Image/><input type="file" accept="image/*" onChange={event=>{attachPhoto(event.target.files?.[0]);event.target.value=''}}/></label><button disabled={!postText.trim()&&!postPhoto}><Send/></button>{postPhoto&&<div className="club-photo-preview"><img src={postPhoto} alt="첨부 사진 미리보기"/><button type="button" onClick={()=>setPostPhoto(null)} aria-label="첨부 사진 삭제"><X/></button></div>}</form>{feed.map(item=><article key={item.id}><i>{item.author.slice(0,1)}</i><div><header><b>{item.author}</b><small>최근 활동</small></header><strong>{item.title}</strong><p>{item.detail}</p>{item.photo&&<img className="club-feed-photo" src={item.photo} alt={`${item.author}님의 활동 사진`}/>}<footer><button className={item.liked?'liked':''} onClick={()=>toggleLike(item.id)}><Heart fill={item.liked?'currentColor':'none'}/> {item.likes}</button><span><MessageCircle/> 댓글 {item.comments}</span></footer></div></article>)}</section>}
  {tab==='album'&&<section className="club-album"><header><div><Image/><span><b>최근 활동 사진</b><small>피드에 올린 사진이 자동으로 모여요</small></span></div><em>총 {38+uploadedPhotos.length}장</em></header><div className="club-album-grid">{albumImages.map((item,index)=><figure key={`${item.src.slice(0,48)}-${index}`}><img src={item.src} alt={`${selected.name} 활동 사진 ${index+1}`}/><figcaption>{item.caption}</figcaption></figure>)}</div><div className="club-recent-projects"><header><h3>최근 연결 프로젝트 <small>{projects.length}개</small></h3>{isChair?<button onClick={()=>setProjectFormOpen(value=>!value)}><Plus/> 프로젝트 추가</button>:<span title="회장만 프로젝트를 추가할 수 있어요"><Crown/> 회장만 추가 가능</span>}</header>{projectFormOpen&&isChair&&<form onSubmit={addLinkedProject}><input autoFocus maxLength={50} value={projectName} onChange={event=>setProjectName(event.target.value)} placeholder="연결할 프로젝트 이름"/><button disabled={!projectName.trim()}>추가</button></form>}{projects.map(project=><article key={project.id}><span>{project.icon}</span><div><b>{project.name}</b><small>{project.status}</small></div></article>)}</div></section>}
  {tab==='members'&&<section className="club-members"><header><Users/><div><b>동아리 구성원</b><small>{isChair?'회장은 구성원의 역할을 변경할 수 있어요.':'역할별로 커뮤니티를 함께 운영해요.'}</small></div></header>{selected.members.map(member=>{const role=memberRole(member);return <article key={member.userId}><i>{member.name.slice(0,1)}</i><div><b>{member.name}</b><small>{member.userId===userId?'나 · ':''}{role==='회장'?'동아리 운영과 프로젝트 연결 담당':role==='임원'?'활동 기록과 정보 공유 지원':'커뮤니티 활동 참여'}</small></div>{isChair&&role!=='회장'?<select className={`role-select role-${role}`} aria-label={`${member.name} 역할 변경`} value={member.role==='executive'?'executive':'member'} onChange={event=>void changeMemberRole(member,event.target.value as 'executive'|'member')}><option value="executive">임원</option><option value="member">부원</option></select>:<span className={`role-${role}`}>{role==='회장'?<Crown/>:role==='임원'?<Shield/>:<Users/>}{role}</span>}</article>})}</section>}
  {tab==='info'&&<section className="club-info"><dl><div><dt>대표 관심사</dt><dd>{selected.interests.map(item=><span key={item}>#{item}</span>)}</dd></div><div><dt>주요 기록</dt><dd>{selected.activity||'활동 후기와 정보 공유'}</dd></div><div><dt>활동 장소</dt><dd>{selected.location||'공동캠퍼스'}</dd></div><div><dt>운영 방식</dt><dd>자율 가입 · 커뮤니티 기록 중심</dd></div></dl></section>}
  <footer className="club-panel-actions"><button className="club-project-link" onClick={goToProject}><span><small>더 큰 활동으로 이어가기</small><b>프로젝트 만들기</b></span><ArrowRight/></button><button className="club-simple-join" disabled={selected.members.some(member=>member.userId===userId)} onClick={()=>void joinClub(selected)}>{selected.members.some(member=>member.userId===userId)?<><Check/> 가입됨</>:<><Plus/> 동아리 가입</>}</button></footer>
 </aside>}
 {creatorOpen&&<div className="club-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setCreatorOpen(false)}}><form className="club-create-modal club-community-create" onSubmit={createClub}><button type="button" className="club-modal-close" onClick={()=>setCreatorOpen(false)}><X/></button><header><span>🌸</span><div><small>NEW COMMUNITY</small><h2>새 동아리 만들기</h2><p>같은 관심사를 꾸준히 기록하고 나누는 커뮤니티를 개설해요.</p></div></header><aside className="club-create-role-guide"><Crown/><div><b>{profile.nickname}님이 회장이 됩니다</b><p>회장은 임원·부원과 활동을 운영하고 동아리에 프로젝트를 연결할 수 있어요.</p></div></aside><section className="club-create-fields"><label><span>동아리명 <em>필수</em></span><input required maxLength={40} value={clubName} onChange={event=>setClubName(event.target.value)} placeholder="예: 세종 사진동아리" autoFocus/></label><label><span>동아리 소개 <em>필수</em></span><textarea required maxLength={180} value={description} onChange={event=>setDescription(event.target.value)} placeholder="예: 세종의 풍경을 함께 기록하고 사진 이야기를 나눠요."/><small>{description.length}/180</small></label><label><span>대표 관심사 <em>필수</em></span><input required maxLength={24} value={interest} onChange={event=>setInterest(event.target.value)} placeholder="예: 사진"/><div className="club-interest-picks">{['사진','카페','꽃·식물','축제','환경·봉사'].map(item=><button type="button" className={interest===item?'active':''} key={item} onClick={()=>setInterest(item)}>{item}</button>)}</div></label><label><span>주로 남길 활동 기록 <em>필수</em></span><input required maxLength={24} value={recordType} onChange={event=>setRecordType(event.target.value)} placeholder="예: 출사, 사진, 후기"/><small>활동 피드와 앨범에서 쌓아갈 기록을 적어주세요.</small></label></section><section className="club-create-preview"><small>부스 미리보기</small><div><i>{interest.includes('사진')?'📸':interest.includes('카페')?'☕':interest.includes('꽃')?'🌸':interest.includes('환경')?'🌱':'🎪'}</i><span><b>{clubName.trim()||'새 동아리'}</b><p>{description.trim()||'동아리 소개가 여기에 표시됩니다.'}</p><em>#{interest||'관심사'} · #{recordType||'활동 기록'}</em></span></div></section><div className="club-create-policy"><Check/><span><b>동아리는 커뮤니티 공간입니다.</b><small>가입, 활동 기록, 사진·후기·정보 공유를 중심으로 운영됩니다.</small></span></div>{createError&&<p className="club-create-error">{createError}</p>}<button className="club-create-submit" disabled={saving||!clubName.trim()||!description.trim()||!interest.trim()||!recordType.trim()}>{saving?'동아리를 만드는 중…':'내 동아리 만들기'}</button></form></div>}
 {boothPickerTarget!==null&&<div className="club-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setBoothPickerTarget(null)}}><section className="club-booth-picker"><button type="button" className="club-modal-close" onClick={()=>setBoothPickerTarget(null)}><X/></button><header><Plus/><div><small>내 동아리 올리기</small><h2>이 부스에 올릴 동아리를 선택하세요</h2></div></header>{myBoothClubs.length?<div>{myBoothClubs.map(club=><button type="button" key={club.id} onClick={()=>placeMyClub(club)}><span>{club.icon}</span><div><b>{club.name}</b><small>{club.category} · {club.description}</small></div><ArrowRight/></button>)}</div>:<p>아직 올릴 수 있는 내 동아리가 없어요.<br/>동아리 창설 부스에서 먼저 만들어 주세요.</p>}</section></div>}
 </div>;
}
