import {useEffect,useMemo,useState,type CSSProperties} from 'react';
import {Check,Heart,Plus,Sparkles,UserPlus,Users,X} from 'lucide-react';
import {gameEvents} from '../game/events';
import './ClubStreetExperience.css';
import './ClubStreetAnchors.css';
import './ClubStreetCommunity.css';

type Club={id:string;icon:string;name:string;score:number;color:string;reasons:string[];activity:string;activityAction:string;current:number;capacity:number;reward:string;members:string[]};
const CLUBS:Club[]=[
 {id:'photo',icon:'📷',name:'사진 동아리',score:92,color:'#7655b5',reasons:['사진 기록 성향 89','야간축제를 저장했어요','탐험형 성향'],activity:'세종 야경 사진 출사',activityAction:'같이 사진 찍기',current:3,capacity:5,reward:'협업 경험 +1',members:['하늘여우','복숭아','AIExplorer']},
 {id:'nature',icon:'🌿',name:'자연기록 동아리',score:94,color:'#6d9f3f',reasons:['수목원 식물도감 12종 완성','자연 감정 기록','탐험형 성향'],activity:'식물도감 같이 완성하기',activityAction:'같이 찾기',current:2,capacity:4,reward:'협업 경험 +1',members:['초록별','하늘여우','나무늘보']},
 {id:'culture',icon:'🎭',name:'공연 동아리',score:91,color:'#dd8738',reasons:['문화 관심 91','공연 기록 4회','활발한 소통 성향'],activity:'세종 축제 같이 보러가기',activityAction:'같이 이동',current:4,capacity:6,reward:'문화 네트워크 +1',members:['복숭아','달빛','StageON']},
 {id:'ai',icon:'💻',name:'AI·개발 동아리',score:87,color:'#3978be',reasons:['AI 관심이 높아요','문제 해결형 성향','프로젝트 경험 2회'],activity:'세종 생활 AI 미니 프로젝트',activityAction:'같이 만들기',current:3,capacity:6,reward:'협업 경험 +1',members:['AIExplorer','코드나무','하늘여우']},
 {id:'local',icon:'🍑',name:'로컬푸드 동아리',score:84,color:'#d65e72',reasons:['로컬푸드 기록 7개','조치원 탐방 완료','기록형 성향'],activity:'조치원 시장 맛지도 만들기',activityAction:'같이 기록하기',current:2,capacity:5,reward:'지역 네트워크 +1',members:['복숭아','세종한입','초록별']},
 {id:'travel',icon:'🧳',name:'여행 동아리',score:89,color:'#5582c7',reasons:['탐험형 성향','여행 코스 3개 저장','문화 관심이 높아요'],activity:'세종 숨은 장소 탐험',activityAction:'같이 둘러보기',current:3,capacity:5,reward:'협업 경험 +1',members:['달빛','길잡이','AIExplorer']},
];
const PEOPLE:Record<string,{interests:string[];similarity:number}>={하늘여우:{interests:['🌿 자연','📸 사진'],similarity:87},복숭아:{interests:['🍑 로컬푸드','🎭 공연'],similarity:82},AIExplorer:{interests:['💻 AI','📸 사진'],similarity:91},초록별:{interests:['🌿 자연','📸 기록'],similarity:89},나무늘보:{interests:['🌿 자연','🧳 여행'],similarity:85},달빛:{interests:['🎭 공연','🧳 여행'],similarity:88},StageON:{interests:['🎭 공연','📸 사진'],similarity:84},코드나무:{interests:['💻 AI','🌿 자연'],similarity:86},세종한입:{interests:['🍑 로컬푸드','📸 기록'],similarity:81},길잡이:{interests:['🧳 여행','🌿 자연'],similarity:83}};

export function ClubStreetExperience({active,onNotice}:{active:boolean;onNotice:(message:string)=>void}){
 const [positions,setPositions]=useState<{x:number;y:number;visible:boolean}[]>([]),[selected,setSelected]=useState<Club|null>(null),[person,setPerson]=useState(''),[joined,setJoined]=useState<string[]>([]),[activityDone,setActivityDone]=useState(false),[creatorOpen,setCreatorOpen]=useState(false),[created,setCreated]=useState(false),[clubName,setClubName]=useState(''),[category,setCategory]=useState('사진'),[description,setDescription]=useState(''),[capacity,setCapacity]=useState(5);
 useEffect(()=>{const changed=(value:{x:number;y:number;visible:boolean}[])=>setPositions(value);gameEvents.on('club-booth-card-screen-positions',changed);return()=>{gameEvents.off('club-booth-card-screen-positions',changed)}},[]);
 useEffect(()=>{if(!active){setSelected(null);setPerson('');setCreatorOpen(false)}},[active]);
 const recommendations=useMemo(()=>category==='사진'?['하늘여우','복숭아']:category==='자연'?['초록별','나무늘보']:category==='AI'?['AIExplorer','코드나무']:['복숭아','달빛'],[category]);
 if(!active)return null;
 const openClub=(club:Club)=>{setSelected(club);setPerson('');setActivityDone(false)};
 return <div className="club-street-ui club-community-ui">
  <section className="club-street-banner"><Sparkles size={17}/><div><b>동아리 거리제</b><span>AI 프로필로 관심사가 같은 사람들과 만나보세요</span></div></section>
  <div className="club-recommendations">{CLUBS.map((club,index)=>{const anchor=positions[index];return <button key={club.id} onClick={()=>openClub(club)} className={`club-booth-label ${anchor&&!anchor.visible?'is-offscreen':''}`} style={{'--club-color':club.color,...(anchor?{left:anchor.x,top:anchor.y}:{})} as CSSProperties}><span>{club.icon}</span><b>{club.name}</b><small>{club.score}%</small></button>})}</div>
  <button className="club-kiosk-button" onClick={()=>setCreatorOpen(true)}><Plus/><span><small>중앙 키오스크</small><b>동아리 만들기</b></span></button>
  <section className="club-profile-strip"><b>내 협업 프로필</b><span>🤝 협업 경험 <strong>{activityDone?4:3}회</strong></span><span>🏠 가입 동아리 <strong>{joined.length}개</strong></span><span>🎯 관심 분야 <strong>사진 · 문화 · AI</strong></span><span>💬 소통 성향 <strong>활발</strong></span></section>
  {selected&&<aside className="club-booth-panel" style={{'--club-color':selected.color} as CSSProperties}><button className="club-panel-close" onClick={()=>setSelected(null)}><X/></button><header><span>{selected.icon}</span><div><small>AI 프로필 매칭</small><h2>{selected.name}</h2><strong>★★★★★ {selected.score}%</strong></div></header><section className="club-match-reasons"><b>현재 나와 잘 맞는 이유</b>{selected.reasons.map(reason=><p key={reason}>✔ {reason}</p>)}<small>가입 여부를 결정하는 참고자료예요.</small></section><section><div className="club-section-title"><b><Users/> 현재 활동</b><span>{selected.members.length}명</span></div><div className="club-active-people">{selected.members.map(name=><button className={person===name?'active':''} onClick={()=>setPerson(name)} key={name}>👤 {name}</button>)}</div>{person&&<div className="club-person-card"><b>{person}</b><p>{(PEOPLE[person]??{interests:['🌿 자연'],similarity:80}).interests.join('　')}</p><strong>나와 유사도 {(PEOPLE[person]??{similarity:80}).similarity}%</strong><button onClick={()=>onNotice(`${person}님에게 같이 둘러보기를 제안했어요.`)}>같이 둘러보기</button></div>}</section><section className="club-group-activity"><div><small>같이 활동하기</small><h3>{selected.activity}</h3><p>현재 <b>{selected.current}/{selected.capacity}명</b></p></div><button onClick={()=>{setActivityDone(true);onNotice(`${selected.reward} · 프로필에 반영됐어요.`)}}>{activityDone?<><Check/> 참여 완료</>:<>{selected.activityAction} →</>}</button>{activityDone&&<strong>{selected.reward}</strong>}</section><button className="club-apply-button" disabled={joined.includes(selected.id)} onClick={()=>setJoined(old=>[...old,selected.id])}><UserPlus/>{joined.includes(selected.id)?'가입 신청 완료':'AI 프로필로 가입 신청'}</button><small className="club-profile-delivery">문화 관심 91 · 자연 관심 95 · 탐험형 · 기록 성향 89가 관리자에게 전달됩니다.</small></aside>}
  {creatorOpen&&<div className="club-modal-backdrop"><section className="club-create-modal"><button className="club-modal-close" onClick={()=>setCreatorOpen(false)}><X/></button><header><span>⭐</span><div><small>CENTRAL KIOSK</small><h2>새 동아리 만들기</h2></div></header>{!created?<><label>동아리 이름<input value={clubName} onChange={e=>setClubName(e.target.value)} placeholder="예: 세종 야경 사진 동아리"/></label><label>관심 분야<select value={category} onChange={e=>setCategory(e.target.value)}>{['사진','문화','AI','자연','로컬푸드'].map(item=><option key={item}>{item}</option>)}</select></label><label>설명<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="어떤 활동을 함께 하나요?"/></label><label>모집 인원<input type="number" min="2" max="30" value={capacity} onChange={e=>setCapacity(Number(e.target.value))}/></label><section className="club-ai-candidates"><Sparkles/><div><b>AI가 추천할 사람 {recommendations.length+10}명 발견</b><p>{recommendations.join(' · ')} 님의 프로필과 잘 맞아요.</p></div></section><button className="club-create-submit" disabled={!clubName.trim()} onClick={()=>setCreated(true)}>동아리 생성하고 추천 대상 초대</button></>:<div className="club-created-result"><div className="club-check"><Check/></div><h2>{clubName} 생성 완료!</h2><p>AI 추천 대상에게 초대를 보냈어요.</p>{recommendations.map(name=><div key={name}><b>👤 {name}</b><span>{PEOPLE[name]?.interests.join(' · ')}</span></div>)}<button onClick={()=>{setCreatorOpen(false);setCreated(false);setClubName('');onNotice('새 동아리가 생성되었어요.')}}>확인</button></div>}</section></div>}
 </div>;
}
