import Phaser from 'phaser';import type { UserProfile } from '../../types';import type { CharacterEmote,Direction,MapId,PlayerState } from '../../../shared/socket-events';import { createAvatar,animateAvatar,type AvatarContainer } from '../entities/createAvatar';import { gameEvents } from '../events';import { socket } from '../systems/socketClient';
import { mapAssetManifest } from '../../data/mapAssetManifest';
import { characterSettings } from '../character/characterSettings';
import { directionFromMovement,directionYaw,jumpInputBlocked,motionState,movementInputBlocked,movementYaw,normalizedMovement,shortestAngleDelta } from '../character/characterMotion';
import { BEAR_PLAY_ZONE_SPAWN,BEAR_TREE_PARK_SPAWN,CAMPUS_SPAWN,GARDEN_SPAWN,GOVERNMENT_CENTRAL_PLAZA_SPAWN,GOVERNMENT_OBSERVATORY_SPAWN,GOVERNMENT_SPAWN,LAKE_PARK_SPAWN,PROJECT_ROOM_SPAWN,PROJECT_ROOM_WORLD_HEIGHT,PROJECT_ROOM_WORLD_WIDTH,RECRUITMENT_CENTER_SPAWN,RECRUITMENT_CENTER_WORLD_HEIGHT,SEJONG_SMART_CITY_SPAWN,STUDENT_HALL_SPAWN,type VillageMapRenderer } from '../renderers/VillageMapRenderer';
import type { GameReturnState } from '../gameReturnState';
import { saveLocalPlayerResumeState } from '../playerResumeState';
interface Remote { avatar:AvatarContainer; targetX:number; targetY:number; targetYaw:number; state:PlayerState;lastAnimationAt:number }
interface SceneData {profile:UserProfile;mapId?:MapId;worldRenderers?:Partial<Record<MapId,VillageMapRenderer>>;ensureWorldRenderer?:(mapId:MapId)=>VillageMapRenderer|undefined;initialSpawn?:{x:number;z:number;yaw:number};previewOnly?:boolean}
const labels:Record<MapId,string>={town:'세종호수공원','arts-center':'세종예술의전당','festival-experience':'축제 부스','food-experience':'먹거리 부스','club-street-festival':'동아리 거리제','bear-tree-park':'베어트리파크','bear-play-zone':'AI 탐험 연구소',garden:'수목원',campus:'공동캠퍼스','student-hall':'학생회관','recruitment-center':'모집센터','project-room':'프로젝트실',government:'정부청사','government-central-plaza':'중앙광장','government-policy-hall':'정책 체험관','government-observatory':'전망대','sejong-smart-city':'세종 스마트시티 국가시범도시','jochwon-station':'조치원역','traditional-market':'세종전통시장','jochwon-park':'조치원공원','college-street':'대학로'};
const MAIN={width:2400,height:1900};const DETAIL={width:1600,height:1100};
const PROJECT_ROOM_SIZE={width:PROJECT_ROOM_WORLD_WIDTH,height:PROJECT_ROOM_WORLD_HEIGHT};
const RECRUITMENT_CENTER_SIZE={width:MAIN.width,height:RECRUITMENT_CENTER_WORLD_HEIGHT};
type DetailMapId=Exclude<MapId,'town'|'arts-center'|'festival-experience'|'food-experience'|'club-street-festival'|'bear-tree-park'|'bear-play-zone'|'garden'|'campus'|'student-hall'|'recruitment-center'|'project-room'|'government'|'government-central-plaza'|'government-observatory'|'sejong-smart-city'>;
type IllustratedDetailMapId=keyof typeof mapAssetManifest;
export class WorldScene extends Phaser.Scene{
 previewOnly=false;
 projectRoomId?:string;
 player!:AvatarContainer;cursors!:Phaser.Types.Input.Keyboard.CursorKeys;keys!:Record<string,Phaser.Input.Keyboard.Key>;profile!:UserProfile;mapId:MapId='town';worldRenderers?:Partial<Record<MapId,VillageMapRenderer>>;ensureWorldRenderer?:SceneData['ensureWorldRenderer'];initialSpawn?:SceneData['initialSpawn'];remotes=new Map<string,Remote>();remoteEmotes=new Map<string,CharacterEmote>();localEmote:CharacterEmote|null=null;emoteTimer?:Phaser.Time.TimerEvent;direction:Direction='right';isMoving=false;transitioning=false;inputLocked=false;encounterPlayerId?:string;targetYaw=LAKE_PARK_SPAWN.yaw;lastSent=0;lastSentX=Number.NaN;lastSentY=Number.NaN;lastSentYaw=LAKE_PARK_SPAWN.yaw;lastSentMotion:'idle'|'walk'|'run'='idle';lastSentJumpHeight=0;groundY=LAKE_PARK_SPAWN.z;jumpHeight=0;jumpVelocity=0;nearbyPlayerId?:string;obstacles:Phaser.Geom.Rectangle[]=[];assetLoadErrors:string[]=[];
 constructor(){super('world')}
 preload(){this.assetLoadErrors=[];this.load.on('loaderror',(file:Phaser.Loader.File)=>{const url=String(file.src);this.assetLoadErrors.push(`${file.key}: ${url}`);console.error('[Phaser asset load error]',{key:file.key,url,type:file.type})});this.load.on('complete',()=>console.log('[Phaser assets loaded successfully]'));Object.values(mapAssetManifest).forEach(asset=>this.load.svg(asset.key,asset.url))}
 init(data:SceneData){this.profile=data.profile;this.mapId=data.mapId??'town';this.previewOnly=!!data.previewOnly;this.worldRenderers=data.worldRenderers??this.worldRenderers;this.ensureWorldRenderer=data.ensureWorldRenderer??this.ensureWorldRenderer;this.initialSpawn=data.initialSpawn;Object.entries(this.worldRenderers??{}).forEach(([mapId,renderer])=>renderer?.setVisible(mapId===this.mapId));this.obstacles=[];this.jumpHeight=0;this.jumpVelocity=0;this.lastSentJumpHeight=0}
 create(){console.log('[Phaser WorldScene create start]',{mapId:this.mapId});try{this.transitioning=false;const threeWorld=!!(this.worldRenderer??this.ensureWorldRenderer?.(this.mapId)),size=threeWorld?(this.mapId==='project-room'?PROJECT_ROOM_SIZE:this.mapId==='recruitment-center'?RECRUITMENT_CENTER_SIZE:MAIN):DETAIL;this.physics.world.setBounds(0,0,size.width,size.height);this.cameras.main.setBounds(0,0,size.width,size.height);threeWorld?this.drawThreeWorld():this.drawDetail();this.scene.setVisible(!threeWorld);const worldSpawns:Partial<Record<MapId,{x:number;z:number;yaw:number}>>={town:LAKE_PARK_SPAWN,'bear-tree-park':BEAR_TREE_PARK_SPAWN,'bear-play-zone':BEAR_PLAY_ZONE_SPAWN,garden:GARDEN_SPAWN,campus:CAMPUS_SPAWN,'student-hall':STUDENT_HALL_SPAWN,'recruitment-center':RECRUITMENT_CENTER_SPAWN,'project-room':PROJECT_ROOM_SPAWN,government:GOVERNMENT_SPAWN,'government-central-plaza':GOVERNMENT_CENTRAL_PLAZA_SPAWN,'government-observatory':GOVERNMENT_OBSERVATORY_SPAWN,'sejong-smart-city':SEJONG_SMART_CITY_SPAWN},worldSpawn=this.initialSpawn??worldSpawns[this.mapId]??LAKE_PARK_SPAWN,spawn=threeWorld?{x:worldSpawn.x,y:worldSpawn.z}:this.initialSpawn?{x:this.initialSpawn.x,y:this.initialSpawn.z}:{x:800,y:880};this.groundY=spawn.y;this.targetYaw=threeWorld?worldSpawn.yaw:0;this.direction=threeWorld?'right':'down';this.player=createAvatar(this,spawn.x,spawn.y,this.profile.character,this.profile.nickname,1.05,this.profile.model,!threeWorld).setDepth(3000);if(threeWorld)this.player.setVisible(false);this.cameras.main.startFollow(this.player,true,.08,.08);this.cursors=this.input.keyboard!.createCursorKeys();this.keys=this.input.keyboard!.addKeys('W,A,S,D,SHIFT,SPACE',false) as Record<string,Phaser.Input.Keyboard.Key>;this.bindInput();if(!this.previewOnly)this.bindSocket();const join=()=>{if(this.previewOnly)return;socket.emit('joinMap',{mapId:this.mapId,nickname:this.profile.nickname,appearance:this.profile.character,model:this.profile.model,x:this.player.x,y:this.groundY})};socket.on('connect',join);if(!this.previewOnly)(socket.connected?join():socket.connect());gameEvents.emit('location-changed',labels[this.mapId]);gameEvents.emit('map-travel-complete',this.mapId);this.events.once(Phaser.Scenes.Events.SHUTDOWN,()=>{socket.off('connect',join);this.cleanup()});if(this.assetLoadErrors.length)this.showDevelopmentError(`일부 맵 에셋을 불러오지 못했습니다.\n${this.assetLoadErrors.join('\n')}`);console.log('[Phaser WorldScene create complete]',{mapId:this.mapId,assetLoadErrors:this.assetLoadErrors})}catch(error){console.error('[Phaser WorldScene create error]',error);gameEvents.emit('map-travel-complete',this.mapId);this.showDevelopmentError(error instanceof Error?error.message:String(error))}}
 get worldRenderer(){return this.worldRenderers?.[this.mapId]}
  bindInput(){this.input.on('pointerdown',()=>{const focused=document.activeElement as HTMLElement|null;if(focused&&focused!==document.body&&!['INPUT','TEXTAREA','SELECT'].includes(focused.tagName))focused.blur()});this.input.on('gameobjectdown',(_:unknown,obj:Phaser.GameObjects.GameObject)=>{if(this.inputLocked)return;const user=obj.getData('network-user');if(user)gameEvents.emit('network-user-selected',user);const destination=obj.getData('destination') as MapId|undefined;if(destination)this.changeMap(destination)});gameEvents.on('show-bubble',this.onShowBubble,this);gameEvents.on('travel-to-map',this.onTravelToMap);gameEvents.on('game-input-lock',this.onInputLock);gameEvents.on('player-encounter-focus',this.onEncounterFocus);gameEvents.on('character-emote-play',this.onCharacterEmotePlay);gameEvents.on('game-return-state-requested',this.onGameReturnStateRequested);gameEvents.on('project-room-entered',this.onProjectRoomEntered)}
 bindSocket(){socket.on('currentMapUsers',this.onCurrentUsers);socket.on('userJoined',this.onUserJoined);socket.on('userMoved',this.onUserMoved);socket.on('userLeft',this.onUserLeft);socket.on('nearbyChat',this.onNearbyChat);socket.on('characterEmoteChanged',this.onCharacterEmoteChanged);gameEvents.on('project-room-instance-enter',this.onProjectRoomInstanceEnter)}
 onProjectRoomInstanceEnter=(projectRoomId:string)=>{if(this.mapId!=='project-room')return;this.projectRoomId=projectRoomId;this.remotes.forEach((_,id)=>this.removeRemote(id));socket.off('userJoined',this.onUserJoined);socket.off('userMoved',this.onUserMoved);socket.on('userJoined',this.onProjectInstanceUserJoined);socket.on('userMoved',this.onProjectInstanceUserMoved);socket.emit('enterProjectRoomInstance',projectRoomId)}
 onProjectInstanceUserJoined=(player:PlayerState)=>{if(player.projectRoomId===this.projectRoomId)this.addRemote(player)}
 onProjectInstanceUserMoved=(player:PlayerState)=>{if(player.projectRoomId===this.projectRoomId)this.moveRemote(player);else this.removeRemote(player.id)}
  cleanup(){gameEvents.off('show-bubble',this.onShowBubble,this);gameEvents.off('travel-to-map',this.onTravelToMap);gameEvents.off('game-input-lock',this.onInputLock);gameEvents.off('player-encounter-focus',this.onEncounterFocus);gameEvents.off('character-emote-play',this.onCharacterEmotePlay);gameEvents.off('game-return-state-requested',this.onGameReturnStateRequested);gameEvents.off('project-room-entered',this.onProjectRoomEntered);socket.off('currentMapUsers',this.onCurrentUsers);socket.off('userJoined',this.onUserJoined);socket.off('userMoved',this.onUserMoved);socket.off('userLeft',this.onUserLeft);socket.off('nearbyChat',this.onNearbyChat);socket.off('characterEmoteChanged',this.onCharacterEmoteChanged);this.emoteTimer?.remove(false);this.remotes.forEach((r,id)=>{r.avatar.destroy();this.worldRenderer?.removeRemoteCharacter(id)});this.remotes.clear();this.remoteEmotes.clear();this.localEmote=null;this.nearbyPlayerId=undefined;this.encounterPlayerId=undefined;gameEvents.emit('nearby-player-changed',null)}
  onGameReturnStateRequested=(callback:(state:GameReturnState)=>void)=>callback({mapId:this.mapId,x:this.player.x,z:this.groundY,yaw:this.targetYaw})
 onInputLock=(locked:boolean)=>{this.inputLocked=locked;if(locked){this.isMoving=false;Object.values(this.keys??{}).forEach(key=>key.reset())}}
 onEncounterFocus=(id:string|null)=>{this.encounterPlayerId=id??undefined}
 onProjectRoomEntered=()=>{if(this.mapId==='project-room'){this.targetYaw=Math.PI/2;this.direction='right'}}
 onCharacterEmotePlay=(emote:CharacterEmote|null)=>{this.emoteTimer?.remove(false);this.localEmote=emote;socket.emit('characterEmote',emote);if(emote&&emote!=='talking'){const duration=emote==='hi'?690:1190;this.emoteTimer=this.time.delayedCall(duration,()=>{this.localEmote=null;socket.emit('characterEmote',null)})}}
 onCharacterEmoteChanged=({playerId,emote}:{playerId:string;emote:CharacterEmote|null})=>{if(playerId===socket.id){this.localEmote=emote;return}if(emote)this.remoteEmotes.set(playerId,emote);else this.remoteEmotes.delete(playerId)}
 onCurrentUsers=(players:PlayerState[])=>{const ids=new Set(players.filter(p=>p.id!==socket.id).map(p=>p.id));for(const [id] of this.remotes)if(!ids.has(id))this.removeRemote(id);players.forEach(p=>this.addRemote(p))};onUserJoined=(p:PlayerState)=>this.addRemote(p);onUserMoved=(p:PlayerState)=>this.moveRemote(p);onUserLeft=(id:string)=>this.removeRemote(id);onNearbyChat=(m:{senderId:string;message:string})=>{const target=m.senderId===socket.id?this.player:this.remotes.get(m.senderId)?.avatar;if(target)this.showBubble(target,m.message);gameEvents.emit('chat-received',m)};onShowBubble=(message:string)=>this.showBubble(this.player,message);
 addRemote(state:PlayerState){if(state.id===socket.id||state.nickname===this.profile.nickname){this.removeRemote(state.id);return}const targetYaw=Number.isFinite(state.yaw)?state.yaw:directionYaw(state.direction),threeWorld=!!this.worldRenderer;const old=this.remotes.get(state.id);if(old){old.targetX=state.x;old.targetY=state.y;old.targetYaw=targetYaw;old.state=state;old.avatar.setData('network-user',state);return}const avatar=createAvatar(this,state.x,state.y,state.appearance,state.nickname,.98,state.model,!threeWorld);if(threeWorld)avatar.setVisible(false);avatar.setData('network-user',state);avatar.setData('visualYaw',targetYaw);this.remotes.set(state.id,{avatar,targetX:state.x,targetY:state.y,targetYaw,state,lastAnimationAt:0})}
 moveRemote(state:PlayerState){const remote=this.remotes.get(state.id);if(!remote)return this.addRemote(state);remote.targetX=state.x;remote.targetY=state.y;remote.targetYaw=Number.isFinite(state.yaw)?state.yaw:directionYaw(state.direction);remote.state=state;remote.avatar.setData('network-user',state)}removeRemote(id:string){this.remotes.get(id)?.avatar.destroy();this.worldRenderer?.removeRemoteCharacter(id);this.remotes.delete(id);this.remoteEmotes.delete(id)}
 drawThreeWorld(){this.cameras.main.setBackgroundColor('rgba(0,0,0,0)')}
 drawDetail(){this.cameras.main.setBackgroundColor('#dce5dd');const configs={
  campus:{color:0x6d8ea0,title:'캠퍼스 · 준비 중',features:['캠퍼스 광장','강의 공간','커뮤니티 라운지']},
  'jochwon-station':{color:0x7b9997,title:'조치원역',features:['안내 데스크','대기 공간','마을 이동 안내']},
  'traditional-market':{color:0xd69a64,title:'세종전통시장',features:['시장 천막','먹거리 골목','상인 쉼터']},
  'jochwon-park':{color:0x7bad72,title:'조치원공원',features:['산책길','연못','벤치']},
  'college-street':{color:0x7c8eb5,title:'대학로',features:['카페 거리','소규모 광장','커뮤니티 공간']},
  'government-policy-hall':{color:0x557a70,title:'정책 체험관',features:['정책 아카이브','시민 의견 보드','행정 데이터 라운지']},
  'government-observatory':{color:0x526d8c,title:'전망대',features:['세종 전경','행정중심 안내','포토 스팟']}
 } as const;const c=configs[this.mapId as DetailMapId];this.add.rectangle(800,550,1500,1000,c.color,.34).setStrokeStyle(8,0xffffff,.7);this.road(800,600,1300,150);c.features.forEach((name,i)=>{const x=350+i*450;this.add.rectangle(x,350,270,190,c.color).setStrokeStyle(5,0xffffff).setInteractive().setData('feature',name);this.obstacles.push(new Phaser.Geom.Rectangle(x-135,255,270,190))});c.features.forEach((name,i)=>this.add.text(350+i*450,350,name,{fontSize:'18px',fontStyle:'bold',color:'#fff'}).setOrigin(.5));this.add.text(800,205,c.title,{fontFamily:'Noto Sans KR, sans-serif',fontSize:'32px',fontStyle:'bold',color:'#214f3f',align:'center'}).setOrigin(.5).setDepth(5000);const governmentDetail=this.mapId==='government-policy-hall'||this.mapId==='government-observatory',exitDestination:MapId=governmentDetail?'government':'town';const exit=this.add.rectangle(800,990,260,70,0x315b59).setStrokeStyle(4,0xffdf83).setInteractive({useHandCursor:true}).setData('destination',exitDestination);this.add.text(exit.x,exit.y,governmentDetail?'정부청사로 돌아가기':'메인 마을로 돌아가기',{fontSize:'17px',fontStyle:'bold',color:'#fff'}).setOrigin(.5)}
 place(x:number,y:number,w:number,h:number,color:number,label:string,destination:IllustratedDetailMapId){const asset=mapAssetManifest[destination];if(this.textures.exists(asset.key))this.add.image(x,y,asset.key).setDisplaySize(w,h);else this.drawFallbackPlace(x,y,w,h,color);this.obstacles.push(new Phaser.Geom.Rectangle(x-w/2+20,y-h/2+20,w-40,h-65));const door=this.add.rectangle(x,y+h/2-35,130,75,0x294c49,.82).setStrokeStyle(4,0xffdf83).setInteractive({useHandCursor:true}).setData('destination',destination);this.add.text(x,y-h/2+70,label,{fontFamily:'Noto Sans KR, sans-serif',fontSize:'32px',fontStyle:'bold',color:'#214f3f',align:'center'}).setOrigin(.5).setDepth(5000);this.add.text(door.x,door.y,'입장',{fontSize:'16px',fontStyle:'bold',color:'#fff'}).setOrigin(.5)}
 drawFallbackPlace(x:number,y:number,w:number,h:number,color:number){this.add.rectangle(x,y,w,h,color).setStrokeStyle(7,0xffffff,.8);this.add.polygon(x,y-h/2,[0,0,w/2,-70,w,0,w/2,70],color+0x101010);for(let offset=-w/3;offset<=w/3;offset+=100)this.add.rectangle(x+offset,y+20,54,70,0xd9edf0).setStrokeStyle(3,0xffffff)}
 destinationPin(x:number,y:number,label:string,destination:IllustratedDetailMapId){const pin=this.add.circle(x,y,34,0x294c49,.92).setStrokeStyle(5,0xffdf83).setInteractive({useHandCursor:true}).setData('destination',destination).setDepth(4500);this.add.text(pin.x,pin.y-54,label,{fontFamily:'Noto Sans KR, sans-serif',fontSize:'17px',fontStyle:'bold',color:'#173b36',backgroundColor:'#ffffffdd',padding:{x:9,y:5}}).setOrigin(.5).setDepth(4500);this.add.text(pin.x,pin.y,'입장',{fontSize:'11px',fontStyle:'bold',color:'#fff'}).setOrigin(.5).setDepth(4501)}
 showDevelopmentError(message:string){this.add.text(20,80,`맵 렌더링 오류\n${message}`,{fontFamily:'monospace',fontSize:'14px',color:'#ffffff',backgroundColor:'#9b2c2c',padding:{x:12,y:10},wordWrap:{width:620}}).setScrollFactor(0).setDepth(10000)}
 road(x:number,y:number,w:number,h:number){this.add.rectangle(x,y,w,h,0x768080).setStrokeStyle(8,0xe9dfbd);if(w>h)for(let px=x-w/2+60;px<x+w/2;px+=90)this.add.rectangle(px,y,42,5,0xfff3bf);else for(let py=y-h/2+60;py<y+h/2;py+=90)this.add.rectangle(x,py,5,42,0xfff3bf)}tree(x:number,y:number){this.add.rectangle(x,y+18,12,44,0x73513c);this.add.circle(x,y-12,32,0x4f9266).setStrokeStyle(4,0x87b879);this.obstacles.push(new Phaser.Geom.Rectangle(x-25,y-40,50,75))}
 onTravelToMap=(mapId:MapId)=>this.changeMap(mapId)
 async changeMap(mapId:MapId){
  if(this.transitioning||mapId===this.mapId)return;
  const sourceMapId=this.mapId;
  if(sourceMapId==='town'&&(mapId==='arts-center'||mapId==='food-experience'||mapId==='festival-experience'))gameEvents.emit('lake-portal-used',mapId);
  this.transitioning=true;gameEvents.emit('map-travel-started',mapId);this.cameras.main.fadeOut(120,22,43,40);
  try{
   const renderer=this.ensureWorldRenderer?.(mapId);
   const minimumTransition=new Promise<void>(resolve=>this.time.delayedCall(320,resolve));
   await Promise.all([renderer?.ready??Promise.resolve(),minimumTransition]);
   if(!this.scene.isActive())return;
   const arrivalSpawn=renderer
    ?renderer.arrivalSpawnFrom(sourceMapId)
    // Illustrated detail maps use the bottom exit as their return portal.
    :{x:800,z:860,yaw:Math.PI};
   this.scene.restart({profile:this.profile,mapId,worldRenderers:this.worldRenderers,ensureWorldRenderer:this.ensureWorldRenderer,initialSpawn:arrivalSpawn,previewOnly:this.previewOnly});
  }catch(error){
   this.transitioning=false;this.cameras.main.fadeIn(120,22,43,40);
   gameEvents.emit('map-travel-failed',{mapId,message:error instanceof Error?error.message:String(error)});
  }
 }
 update(time:number,deltaMs:number){
  const focused=document.activeElement as HTMLElement|null,deltaSeconds=Math.min(deltaMs/1000,.05),active=movementInputBlocked(this.inputLocked,focused);
  const movement=normalizedMovement({left:!active&&(this.cursors.left.isDown||this.keys.A.isDown),right:!active&&(this.cursors.right.isDown||this.keys.D.isDown),up:!active&&(this.cursors.up.isDown||this.keys.W.isDown),down:!active&&(this.cursors.down.isDown||this.keys.S.isDown)});
  if(this.previewOnly&&this.worldRenderer){
    this.worldRenderer.updatePreviewCamera(movement.x,movement.y,this.keys.SHIFT.isDown,deltaSeconds);
    return;
  }
  if(!jumpInputBlocked(this.inputLocked,focused)&&Phaser.Input.Keyboard.JustDown(this.keys.SPACE)&&this.jumpHeight<=.01){this.jumpVelocity=300}
  if(this.jumpVelocity!==0||this.jumpHeight>0){
    this.jumpVelocity-=980*deltaSeconds;this.jumpHeight+=this.jumpVelocity*deltaSeconds;
    if(this.jumpHeight<=0){this.jumpHeight=0;this.jumpVelocity=0}
  }
  const worldMovement=this.worldRenderer?.movementFromScreen(movement.x,movement.y)??{x:movement.x,z:movement.y};
  this.isMoving=!!(movement.x||movement.y);const running=this.isMoving&&this.keys.SHIFT.isDown,state=motionState(movement,running);
  if(this.isMoving){
    this.targetYaw=movementYaw({x:worldMovement.x,y:worldMovement.z});this.direction=directionFromMovement(movement,this.direction);
    const size=this.worldRenderer?(this.mapId==='project-room'?PROJECT_ROOM_SIZE:this.mapId==='recruitment-center'?RECRUITMENT_CENTER_SIZE:MAIN):DETAIL,speed=running?characterSettings.runSpeed:characterSettings.walkSpeed,nextX=Phaser.Math.Clamp(this.player.x+worldMovement.x*speed*deltaSeconds,35,size.width-35),nextY=Phaser.Math.Clamp(this.groundY+worldMovement.z*speed*deltaSeconds,90,size.height-35);
    if(this.worldRenderer){this.player.x=nextX;this.groundY=nextY}else{if(this.jumpHeight>8||this.canMove(nextX,this.groundY))this.player.x=nextX;if(this.jumpHeight>8||this.canMove(this.player.x,nextY))this.groundY=nextY}
  }
  const focusedRemote=this.encounterPlayerId?this.remotes.get(this.encounterPlayerId):undefined;
  if(focusedRemote)this.targetYaw=Math.atan2(focusedRemote.avatar.x-this.player.x,focusedRemote.targetY-this.groundY);
  if(this.worldRenderer){const resolved=this.worldRenderer.updateLocalCharacter(this.player.x,this.groundY,this.targetYaw,state,deltaSeconds,this.jumpHeight,this.localEmote);this.player.x=resolved.x;this.groundY=resolved.z}
  this.player.y=this.groundY-this.jumpHeight;
  if(this.mapId!=='town')animateAvatar(this.player,{targetYaw:this.targetYaw,movementX:worldMovement.x,movementY:worldMovement.z,motionState:state},deltaSeconds);
  this.player.setDepth(Math.floor(this.groundY)+2000);
  if(this.shouldSendMovement(time,state)){
    saveLocalPlayerResumeState(this.profile.nickname,{mapId:this.mapId,x:this.player.x,z:this.groundY,yaw:this.targetYaw});
    socket.emit('userMoved',{mapId:this.mapId,x:this.player.x,y:this.groundY,direction:this.direction,isMoving:this.isMoving,yaw:this.targetYaw,motionState:state,jumpHeight:this.jumpHeight,timestamp:Date.now()});
  }
  const interpolation=1-Math.exp(-12*deltaSeconds),animationInterval=1000/30;
  this.remotes.forEach((remote,id)=>{
    remote.avatar.x=Phaser.Math.Linear(remote.avatar.x,remote.targetX,interpolation);remote.avatar.y=Phaser.Math.Linear(remote.avatar.y,remote.targetY-(remote.state.jumpHeight??0),interpolation);remote.avatar.setDepth(Math.floor(remote.targetY)+2000);
    const focused=id===this.encounterPlayerId,remoteYaw=focused?Math.atan2(this.player.x-remote.avatar.x,this.groundY-remote.targetY):remote.targetYaw,remoteState=focused?'idle':remote.state.motionState??(remote.state.isMoving?'walk':'idle');
    if(this.worldRenderer)this.worldRenderer.updateRemoteCharacter(id,remote.state.nickname,remote.state.model,remote.state.appearance,remote.avatar.x,remote.targetY,remoteYaw,remoteState,deltaSeconds,remote.state.jumpHeight??0,this.remoteEmotes.get(id)??null);
    else{const visible=this.cameras.main.worldView.contains(remote.avatar.x,remote.avatar.y);remote.avatar.setVisible(visible);if(visible&&time-remote.lastAnimationAt>=animationInterval){animateAvatar(remote.avatar,{targetYaw:remoteYaw,movementX:Math.sin(remoteYaw),movementY:Math.cos(remoteYaw),motionState:remoteState},Math.min((time-remote.lastAnimationAt)/1000,.05));remote.lastAnimationAt=time}}
  })
  let closest:Remote|undefined,closestDistance=Number.POSITIVE_INFINITY;
  this.remotes.forEach(remote=>{const distance=Math.hypot(remote.avatar.x-this.player.x,remote.targetY-this.groundY);if(distance<closestDistance){closest=remote;closestDistance=distance}});
  const openDistance=220,exitDistance=270,nextNearby=closest&&closestDistance<(closest.state.id===this.nearbyPlayerId?exitDistance:openDistance)?closest:undefined;
  if(nextNearby?.state.id!==this.nearbyPlayerId){this.nearbyPlayerId=nextNearby?.state.id;gameEvents.emit('nearby-player-changed',nextNearby?.state??null)}
 }
 shouldSendMovement(time:number,state:'idle'|'walk'|'run'){if(this.previewOnly)return false;const stateChanged=state!==this.lastSentMotion,moved=!Number.isFinite(this.lastSentX)||Math.hypot(this.player.x-this.lastSentX,this.groundY-this.lastSentY)>=2,turned=Math.abs(shortestAngleDelta(this.lastSentYaw,this.targetYaw))>=.04,jumped=Math.abs(this.jumpHeight-this.lastSentJumpHeight)>=2,heartbeat=time-this.lastSent>=1000,dynamicChanged=stateChanged||moved||turned||jumped;if(dynamicChanged&&time-this.lastSent<67||!dynamicChanged&&!heartbeat)return false;this.lastSent=time;this.lastSentX=this.player.x;this.lastSentY=this.groundY;this.lastSentYaw=this.targetYaw;this.lastSentMotion=state;this.lastSentJumpHeight=this.jumpHeight;return true}
 canMove(x:number,y:number){
  const body=new Phaser.Geom.Rectangle(x-16,y-62,32,72),currentBody=new Phaser.Geom.Rectangle(this.player.x-16,this.groundY-62,32,72);
  const overlapArea=(candidate:Phaser.Geom.Rectangle,wall:Phaser.Geom.Rectangle)=>{const left=Math.max(candidate.left,wall.left),right=Math.min(candidate.right,wall.right),top=Math.max(candidate.top,wall.top),bottom=Math.min(candidate.bottom,wall.bottom);return Math.max(0,right-left)*Math.max(0,bottom-top)};
  return this.obstacles.every(wall=>{const nextOverlap=overlapArea(body,wall);return nextOverlap===0||nextOverlap<overlapArea(currentBody,wall)});
 }
 showBubble(target:Phaser.GameObjects.Container,message:string){const bubble=this.add.text(target.x,target.y-105,message,{fontSize:'14px',color:'#183b36',backgroundColor:'#ffffff',padding:{x:10,y:7},wordWrap:{width:180}}).setOrigin(.5).setDepth(7000);this.tweens.add({targets:bubble,y:bubble.y-12,alpha:0,delay:3200,duration:800,onComplete:()=>bubble.destroy()})}
}
