import '@google/model-viewer';
import type { ModelViewerElement } from '@google/model-viewer';
import { useEffect,useRef,useState } from 'react';
import idleUrl from '../assets/characters/chungnyeong_idle.glb?url';import walkUrl from '../assets/characters/chungnyeong_walk.glb?url';import runUrl from '../assets/characters/chungnyeong_run.glb?url';
import type { MotionState } from '../../shared/socket-events';
import { characterSettings } from '../game/character/characterSettings';
import { movementYaw,motionState,normalizedMovement,smoothAngle,yawDegrees } from '../game/character/characterMotion';
import { CHARACTER_ANIMATION_CLIP,CHARACTER_MODEL_FILES } from '../game/entities/createAvatar';
import { CharacterDebugPanel } from '../components/CharacterDebugPanel';
const urls:Record<MotionState,string>={idle:idleUrl,walk:walkUrl,run:runUrl};
export function CharacterTestPage(){
 const host=useRef<HTMLDivElement>(null),model=useRef<ModelViewerElement|null>(null),keys=useRef(new Set<string>()),stateRef=useRef<MotionState>('idle'),yawRef=useRef(0),positionRef=useRef({x:0,y:0});const [view,setView]=useState({x:0,y:0,yaw:0,state:'idle' as MotionState});
 useEffect(()=>{if(!host.current)return;const element=document.createElement('model-viewer') as ModelViewerElement;model.current=element;element.src=idleUrl;element.alt='충녕이 방향 테스트';element.cameraControls=true;element.environmentImage='neutral';element.animationName=CHARACTER_ANIMATION_CLIP;element.autoplay=true;Object.assign(element.style,{width:'260px',height:'340px'});element.addEventListener('load',()=>{console.log('[Character test] clips',element.availableAnimations);element.animationName=CHARACTER_ANIMATION_CLIP;element.play({repetitions:Infinity,pingpong:false})});host.current.append(element);
  const down=(event:KeyboardEvent)=>{if(['KeyW','KeyA','KeyS','KeyD','ShiftLeft','ShiftRight'].includes(event.code)){keys.current.add(event.code);event.preventDefault()}},up=(event:KeyboardEvent)=>keys.current.delete(event.code);window.addEventListener('keydown',down);window.addEventListener('keyup',up);let frame=0,last=performance.now(),lastUi=0;
  const tick=(now:number)=>{const delta=Math.min((now-last)/1000,.05);last=now;const movement=normalizedMovement({left:keys.current.has('KeyA'),right:keys.current.has('KeyD'),up:keys.current.has('KeyW'),down:keys.current.has('KeyS')}),running=keys.current.has('ShiftLeft')||keys.current.has('ShiftRight'),next=motionState(movement,running);if(movement.x||movement.y)yawRef.current=smoothAngle(yawRef.current,movementYaw(movement),characterSettings.rotationSpeed,delta);const speed=next==='run'?characterSettings.runSpeed:next==='walk'?characterSettings.walkSpeed:0;positionRef.current.x+=movement.x*speed*delta;positionRef.current.y+=movement.y*speed*delta;if(next!==stateRef.current){stateRef.current=next;element.src=urls[next]}element.cameraOrbit=`${yawDegrees(-yawRef.current+characterSettings.modelForwardOffset)}deg 78deg auto`;element.timeScale=next==='run'?characterSettings.runAnimationTimeScale:next==='walk'?characterSettings.walkAnimationTimeScale:1;element.style.transform=`scale(${characterSettings.visualScale}) translateY(${characterSettings.visualOffsetY}px)`;if(now-lastUi>100){lastUi=now;setView({x:positionRef.current.x,y:positionRef.current.y,yaw:yawRef.current,state:next});window.dispatchEvent(new CustomEvent('character-debug-frame',{detail:{file:CHARACTER_MODEL_FILES[next],position:positionRef.current,yaw:yawRef.current,targetYaw:movement.x||movement.y?movementYaw(movement):yawRef.current,motionState:next,clip:CHARACTER_ANIMATION_CLIP,movement,speed,deltaTime:delta,availableClips:element.availableAnimations,rootMotionDetected:false}}))}frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);
  return()=>{cancelAnimationFrame(frame);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);element.remove()}},[]);
 const force=(state:MotionState)=>{stateRef.current=state;if(model.current)model.current.src=urls[state]};
 return <main className="character-test-page"><header><h1>GLB Character Direction Test</h1><p>WASD 이동 · Shift + 방향키 달리기 · 모델을 드래그해 카메라 확인</p></header><section className="character-test-stage"><div className="test-grid"><i className="axis axis-x">+X →</i><i className="axis axis-z">+Y(screen) ↓</i><div className="test-player" style={{transform:`translate(${view.x*.25}px,${view.y*.25}px)`}}><div ref={host}/><i className="test-arrow facing" style={{transform:`rotate(${-yawDegrees(view.yaw)}deg)`}}>↑</i></div></div><div className="test-controls"><b>{view.state.toUpperCase()}</b><button onClick={()=>force('idle')}>Idle</button><button onClick={()=>force('walk')}>Walk</button><button onClick={()=>force('run')}>Run</button></div></section><CharacterDebugPanel/></main>;
}
